spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
  #    hikari:
  #      maximum-pool-size: 50
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
  jpa:
    platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


server:
  port: 8080

h2-server:
  port: 8081